[pytest]
addopts = -v --maxfail=5 --html=Reports/HTML_Report.html
markers = 
    great : used for tests that use the greater than operators
    less : used for tests that use the less than operators
    activity : used to mark tests as activities